[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["python3 -m venv .venv", ". .venv/bin/activate && pip install -r backend/requirements.txt"]

[start]
cmd = ". .venv/bin/activate && cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
